I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 39, in script
    e "I NEED TO EQUIP SOMETHING OR ADO SAJDO PSJKAO PKASD"
  File "renpy/common/00action_other.rpy", line 619, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/inventory.rpy", line 58, in consume
    target.add_hp(self.regen)
  File "game/player.rpy", line 17, in add_hp
    self.hp += consumable.regen
NameError: name 'consumable' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 39, in script
    e "I NEED TO EQUIP SOMETHING OR ADO SAJDO PSJKAO PKASD"
  File "S:\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "S:\renpy-8.3.7-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "S:\renpy-8.3.7-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "S:\renpy-8.3.7-sdk\renpy\character.py", line 1471, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "S:\renpy-8.3.7-sdk\renpy\character.py", line 1117, in do_display
    display_say(who,
  File "S:\renpy-8.3.7-sdk\renpy\character.py", line 814, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "S:\renpy-8.3.7-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "S:\renpy-8.3.7-sdk\renpy\display\core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "S:\renpy-8.3.7-sdk\renpy\display\core.py", line 3289, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "S:\renpy-8.3.7-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "S:\renpy-8.3.7-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "S:\renpy-8.3.7-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "S:\renpy-8.3.7-sdk\renpy\display\screen.py", line 794, in event
    rv = self.child.event(ev, x, y, st)
  File "S:\renpy-8.3.7-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "S:\renpy-8.3.7-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "S:\renpy-8.3.7-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "S:\renpy-8.3.7-sdk\renpy\display\behavior.py", line 1182, in event
    return handle_click(self.clicked)
  File "S:\renpy-8.3.7-sdk\renpy\display\behavior.py", line 1103, in handle_click
    rv = run(action)
  File "S:\renpy-8.3.7-sdk\renpy\display\behavior.py", line 394, in run
    new_rv = run(i, *args, **kwargs)
  File "S:\renpy-8.3.7-sdk\renpy\display\behavior.py", line 401, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 619, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/inventory.rpy", line 58, in consume
    target.add_hp(self.regen)
  File "game/player.rpy", line 17, in add_hp
    self.hp += consumable.regen
NameError: name 'consumable' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
Palmr Quest 1.0
Sat May 31 15:32:06 2025
